FROM ubuntu:16.04

# We need in Mongo and Ruby for application.
# So, let's update the repo cache and install the requested packages

RUN apt-get update
RUN apt-get install -y mongodb-server ruby-full ruby-dev build-essential git
RUN gem install rubygems-update

RUN gem environment
RUN update_rubygems
# RUN gem sources --list
RUN gem update --system
# RUN gem outdated

RUN gem install bcrypt -v '3.1.11' --source 'https://rubygems.org/'
RUN gem install bson -v '4.2.2' --source 'https://rubygems.org/'
RUN gem install bson_ext -v '1.5.1' --source 'https://rubygems.org/'
RUN gem install puma -v '3.10.0' --source 'https://rubygems.org/'

RUN gem install bundler

# Upload the application to container

RUN git clone https://github.com/Artemmkin/reddit.git

# Copy the config files to container

COPY mongod.conf /etc/mongod.conf
COPY db_config /app/db_config
COPY start.sh /start.sh

# Set the application dependencies and make configuration

RUN cd /reddit && bundle install
RUN mkdir -p /data/db
RUN chmod 0777 /start.sh

# Run service during the container start up

CMD ["/start.sh"]

